# The title is the title of your Add-On
title: Summarize
# The description will be shown above the form when activating the Add-On
description: This add-on will provide a short summary of each document you run it on in a text reprt.
# Top level type should always be object
type: object
# How does this add-on accept documents
# If more than one type is specified, the user will be prompted to choose one
documents:
  # By the currently selected documents
  - selected
